package com.cheqi.sdk.models;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.util.List;
import java.util.Objects;

/**
 * Identifies the customer receiving the receipt. Cheqi uses these details to
 * match the customer to their device and deliver the encrypted receipt.
 *
 * <p>At least one identifier must be provided. The system tries them in priority
 * order: pairing code → card details → payment account → email.</p>
 *
 * <h3>Typical usage:</h3>
 * <pre>
 * // In-store: match by card (POS terminals)
 * IdentificationDetails id = IdentificationDetails.builder()
 *     .paymentType(PaymentType.CARD_PAYMENT)
 *     .cardDetails(CardDetails.builder()
 *         .paymentAccountReference("5001A3EEFB8G9CO1MOS7G684GU2DU")
 *         .cardProvider(CardProvider.MASTERCARD)
 *         .build())
 *     .build();
 *
 * // E-commerce: match by pairing code (customer enters code at checkout)
 * IdentificationDetails id = IdentificationDetails.builder()
 *     .paymentType(PaymentType.CARD_PAYMENT)
 *     .pairingCode("84739201")
 *     .build();
 *
 * // Fallback: match by email
 * IdentificationDetails id = IdentificationDetails.builder()
 *     .paymentType(PaymentType.CARD_PAYMENT)
 *     .recipientEmail("customer@example.com")
 *     .build();
 *
 * // Combined: try card first, fall back to email
 * IdentificationDetails id = IdentificationDetails.builder()
 *     .paymentType(PaymentType.CARD_PAYMENT)
 *     .cardDetails(CardDetails.builder()
 *         .paymentAccountReference("5001A3EEFB8G9CO1MOS7G684GU2DU")
 *         .cardProvider(CardProvider.VISA)
 *         .build())
 *     .recipientEmail("customer@example.com")
 *     .build();
 * </pre>
 *
 * <h3>Fields:</h3>
 * <ul>
 *   <li><strong>paymentType</strong> (mandatory): The type of payment (e.g. {@link PaymentType#CARD_PAYMENT})</li>
 *   <li><strong>cardDetails</strong>: Card identification via PAR, PAN, or last four digits. Best for POS/in-store.</li>
 *   <li><strong>pairingCode</strong>: Temporary 8-digit code generated by the customer in the Cheqi app. Best for e-commerce.</li>
 *   <li><strong>paymentAccountDetails</strong>: IBAN or WERO payment account identification</li>
 *   <li><strong>recipientEmail</strong>: Customer email address as fallback identifier</li>
 *   <li><strong>paymentIds</strong>: Additional payment reference identifiers</li>
 *   <li><strong>cheqiReceiptId</strong>: Reference to an existing receipt (used for credit notes)</li>
 * </ul>
 *
 * @see CardDetails
 * @see PaymentAccountDetails
 * @see PaymentType
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IdentificationDetails.Builder.class)
public final class IdentificationDetails {

    /**
     * The type of payment being processed (mandatory).
     */
    @JsonProperty("paymentType")
    private final PaymentType paymentType;

    /**
     * Card identification details (PAR, PAN, last four digits).
     * Used by POS terminals that can read card data.
     */
    @JsonProperty("cardDetails")
    private final CardDetails cardDetails;

    /**
     * Payment account identification (IBAN, WERO).
     * Used for direct debit or bank transfer payments.
     */
    @JsonProperty("paymentAccountDetails")
    private final PaymentAccountDetails paymentAccountDetails;

    /**
     * Additional payment reference identifiers.
     */
    @JsonProperty("paymentIds")
    private final List<String> paymentIds;

    /**
     * Customer email address. Used as a fallback identifier when card or
     * pairing code is not available.
     */
    @JsonProperty("recipientEmail")
    private final String recipientEmail;

    /**
     * Reference to an existing Cheqi receipt. Used when issuing credit notes
     * linked to a previous receipt.
     */
    @JsonProperty("cheqiReceiptId")
    private final String cheqiReceiptId;

    /**
     * Temporary 8-digit pairing code generated by the customer in the Cheqi app.
     * Ideal for e-commerce where the merchant cannot read card details directly.
     * The code expires after 5 minutes.
     */
    @JsonProperty("pairingCode")
    private final String pairingCode;

    // ===== CONSTRUCTOR =====
    private IdentificationDetails(
            PaymentType paymentType,
            CardDetails cardDetails,
            PaymentAccountDetails paymentAccountDetails,
            List<String> paymentIds,
            String recipientEmail,
            String cheqiReceiptId,
            String pairingCode
    ) {
        this.paymentType = paymentType;
        this.cardDetails = cardDetails;
        this.paymentAccountDetails = paymentAccountDetails;
        this.paymentIds = paymentIds;
        this.recipientEmail = recipientEmail;
        this.cheqiReceiptId = cheqiReceiptId;
        this.pairingCode = pairingCode;
    }

    // ===== MANDATORY FIELD ACCESSORS =====
    public PaymentType getPaymentType() {
        return paymentType;
    }

    // ===== OPTIONAL FIELD ACCESSORS =====

    public CardDetails getCardDetails() {
        return cardDetails;
    }

    public PaymentAccountDetails getPaymentAccountDetails() {
        return paymentAccountDetails;
    }

    public List<String> getPaymentIds() {
        return paymentIds;
    }

    public String getRecipientEmail() {
        return recipientEmail;
    }

    public String getCheqiReceiptId() {
        return cheqiReceiptId;
    }

    public String getPairingCode() {
        return pairingCode;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IdentificationDetails && equalTo((IdentificationDetails) other);
    }

    private boolean equalTo(IdentificationDetails other) {
        return Objects.equals(this.paymentType, other.paymentType)
                && Objects.equals(this.cardDetails, other.cardDetails)
                && Objects.equals(this.paymentAccountDetails, other.paymentAccountDetails)
                && Objects.equals(this.paymentIds, other.paymentIds)
                && Objects.equals(this.recipientEmail, other.recipientEmail)
                && Objects.equals(this.cheqiReceiptId, other.cheqiReceiptId)
                && Objects.equals(this.pairingCode, other.pairingCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.paymentType, this.cardDetails, this.paymentAccountDetails, this.paymentIds, this.recipientEmail, this.cheqiReceiptId, this.pairingCode);
    }

    @Override
    public String toString() {
        return "IdentificationDetails{" +
                "paymentType=" + paymentType +
                ", cardDetails=" + cardDetails +
                ", paymentAccountDetails=" + paymentAccountDetails +
                ", paymentIds=" + paymentIds +
                ", recipientEmail=" + recipientEmail +
                ", cheqiReceiptId=" + cheqiReceiptId +
                ", pairingCode=" + pairingCode +
                '}';
    }

    public static IdentificationDetails.Builder builder() {
        return new IdentificationDetails.Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private PaymentType paymentType;
        private CardDetails cardDetails;
        private PaymentAccountDetails paymentAccountDetails;
        private List<String> paymentIds;
        private String recipientEmail;
        private String cheqiReceiptId;
        private String pairingCode;

        private Builder() {
        }

        public IdentificationDetails.Builder from(IdentificationDetails other) {
            paymentType(other.getPaymentType());
            cardDetails(other.getCardDetails());
            paymentAccountDetails(other.getPaymentAccountDetails());
            paymentIds(other.getPaymentIds());
            recipientEmail(other.getRecipientEmail());
            cheqiReceiptId(other.getCheqiReceiptId());
            pairingCode(other.getPairingCode());
            return this;
        }

        /**
         * Sets the payment type (mandatory).
         * @param paymentType The payment type (e.g. {@link PaymentType#CARD_PAYMENT})
         */
        @JsonSetter(value = "paymentType", nulls = Nulls.SKIP)
        public IdentificationDetails.Builder paymentType(PaymentType paymentType) {
            this.paymentType = paymentType;
            return this;
        }

        /**
         * Sets card details for POS/in-store payments where the terminal can read card data.
         * @param cardDetails Card identification (PAR, PAN, or last four digits)
         * @see CardDetails#builder()
         */
        @JsonSetter(value = "cardDetails", nulls = Nulls.SKIP)
        public IdentificationDetails.Builder cardDetails(CardDetails cardDetails) {
            this.cardDetails = cardDetails;
            return this;
        }

        /**
         * Sets payment account details for IBAN or WERO-based payments.
         * @param paymentAccountDetails The payment account identification
         */
        @JsonSetter(value = "paymentAccountDetails", nulls = Nulls.SKIP)
        public IdentificationDetails.Builder paymentAccountDetails(PaymentAccountDetails paymentAccountDetails) {
            this.paymentAccountDetails = paymentAccountDetails;
            return this;
        }

        /**
         * Sets additional payment reference identifiers.
         * @param paymentIds List of payment reference strings
         */
        @JsonSetter(value = "paymentIds", nulls = Nulls.SKIP)
        public IdentificationDetails.Builder paymentIds(List<String> paymentIds) {
            this.paymentIds = paymentIds;
            return this;
        }

        /**
         * Sets the customer's email address as a fallback identifier.
         * Used when card details or pairing code are not available.
         * @param recipientEmail Customer email address
         */
        @JsonSetter(value = "recipientEmail", nulls = Nulls.SKIP)
        public IdentificationDetails.Builder recipientEmail(String recipientEmail) {
            this.recipientEmail = recipientEmail;
            return this;
        }

        /**
         * Sets a reference to an existing Cheqi receipt. Used when issuing credit notes.
         * @param cheqiReceiptId The Cheqi receipt ID (e.g. "CHQ-20260309-123456-AB1234")
         */
        @JsonSetter(value = "cheqiReceiptId", nulls = Nulls.SKIP)
        public IdentificationDetails.Builder cheqiReceiptId(String cheqiReceiptId) {
            this.cheqiReceiptId = cheqiReceiptId;
            return this;
        }

        /**
         * Sets a temporary pairing code from the customer's Cheqi app.
         * Ideal for e-commerce checkout where the merchant cannot read card details.
         * The customer generates this 8-digit code in their Cheqi app by selecting
         * a card and tapping "Generate Pairing Code". The code expires after 5 minutes.
         * @param pairingCode The 8-digit pairing code (e.g. "84739201")
         */
        @JsonSetter(value = "pairingCode", nulls = Nulls.SKIP)
        public IdentificationDetails.Builder pairingCode(String pairingCode) {
            this.pairingCode = pairingCode;
            return this;
        }

        public IdentificationDetails build() {
            return new IdentificationDetails(paymentType, cardDetails, paymentAccountDetails, paymentIds, recipientEmail, cheqiReceiptId, pairingCode);
        }
    }
}
